name: DNSFilter/ipify-api/deploy
on:
  workflow_dispatch:
    inputs:
      project_name:
        required: false
        default: ip
      image_test:
        required: false
        default: cimg/go:1.19.3
      image_machine:
        required: false
        default: ubuntu-2204:2022.04.2
      image_deploy:
        required: false
        default: cimg/deploy:2022.06.1
      helm_chart_version:
        required: false
        default: 0.2.0
      domain:
        required: false
        default: dnsfilter.sh
jobs:
  deploy-prod-k8s:
    if: # GitHub does not currently support regular expressions inside if conditions
#         (github.ref == 'refs/tags//^v.*$/') && (github.ref != 'refs/heads//.*/')
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:
      AWS_ACCOUNT:
      AWS_REGION_NON_PROD:
      AWS_REGION_PROD:
      AWS_ROLE_ARN:
      AWS_ROLE_SESSION_NAME:
      AWS_SECRET_ACCESS_KEY:
      CLUSTER_NAME_APPS_PROD:
      CLUSTER_NAME_PLATFORM:
      GITHUB_ACCESS_TOKEN:
      GITHUB_USER:
      TERRAFORM_TOKEN:
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: |-
        sudo apt update
        sudo apt install -y awscli docker
    - name: Setup AWS assume role
      run: |-
        read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
          < <(aws sts assume-role-with-web-identity \
              --role-arn "${AWS_ROLE_ARN}" \
              --role-session-name "${AWS_ROLE_SESSION_NAME}" \
              --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
              "$@" \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
        if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
            echo "Failed to assume role"
            exit 1
        else
            {
                echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
                echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
                echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
            } >>"$BASH_ENV"
            echo "Assume role with web identity succeeded"
        fi
    - name: Release to prod
      run: |-
        source ${BASH_ENV}
        sudo apt update
        aws ecr get-login-password --region ${AWS_REGION_PROD} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/
        docker pull ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.sha }}
        docker tag ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.sha }} ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.ref }}
        docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.ref }}
    - name: Update kubeconfig and install helm chart
      run: "curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null\nsudo apt install apt-transport-https --yes\necho \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main\" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list\nsudo apt update\nsudo apt install -y helm\naws eks --region ${AWS_REGION_PROD} update-kubeconfig --name ${CLUSTER_NAME_PLATFORM}\nhelm repo add dnsfilter https://raw.githubusercontent.com/DNSFilter/iac_helm_charts/main/ --username ${GITHUB_USER} --password ${GITHUB_ACCESS_TOKEN}\nhelm repo update \nhelm upgrade -i ${{ inputs.project_name }} -f ./iac/kubernetes/values-prod.yaml dnsfilter/service --version ${{ inputs.helm_chart_version }} --set image.tag=${{ github.ref }} -n ip --force"
  deploy-stg-k8s:
    if: # GitHub does not currently support regular expressions inside if conditions
#         (github.ref == 'refs/tags//^rc-.*$/') && (github.ref != 'refs/heads//.*/')
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT:
      AWS_DEFAULT_REGION:
      AWS_REGION_NON_PROD:
      AWS_REGION_PROD:
      AWS_ROLE_ARN:
      AWS_ROLE_SESSION_NAME:
      CLUSTER_NAME_APPS_NON_PROD:
      GITHUB_ACCESS_TOKEN:
      GITHUB_USER:
      TERRAFORM_TOKEN:
      TF_VAR_dnsimple_account:
      TF_VAR_dnsimple_token:
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: |-
        sudo apt update
        sudo apt install -y awscli docker
    - name: Setup AWS assume role
      run: |-
        read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
          < <(aws sts assume-role-with-web-identity \
              --role-arn "${AWS_ROLE_ARN}" \
              --role-session-name "${AWS_ROLE_SESSION_NAME}" \
              --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
              "$@" \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
        if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
            echo "Failed to assume role"
            exit 1
        else
            {
                echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
                echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
                echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
            } >>"$BASH_ENV"
            echo "Assume role with web identity succeeded"
        fi
    - name: Docker tag and push for staging
      run: |-
        source ${BASH_ENV}
        aws ecr get-login-password --region ${AWS_REGION_PROD} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/
        docker pull ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.sha }}
        docker tag ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.sha }} ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.ref }}
        docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.ref }}
    - name: Update kubeconfig and deploy
      run: "curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null\nsudo apt install apt-transport-https --yes\necho \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main\" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list\nsudo apt update\nsudo apt install -y helm\naws eks --region ${AWS_REGION_NON_PROD} update-kubeconfig --name ${CLUSTER_NAME_APPS_NON_PROD}\nhelm repo add dnsfilter https://raw.githubusercontent.com/DNSFilter/iac_helm_charts/main/ --username ${GITHUB_USER} --password ${GITHUB_ACCESS_TOKEN}\nhelm repo update \nhelm upgrade -i ${{ inputs.project_name }} -f ./iac/kubernetes/values-staging.yaml dnsfilter/service --version ${{ inputs.helm_chart_version }} --set image.tag=${{ github.ref }} --set ingressHost=\"${{ inputs.project_name }}.stg.${{ inputs.domain }}\" -n staging"
  build-push-docker-image:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT:
      AWS_DEFAULT_REGION:
      AWS_REGION_NON_PROD:
      AWS_REGION_PROD:
      AWS_ROLE_ARN:
      AWS_ROLE_SESSION_NAME:
      CLUSTER_NAME_APPS_NON_PROD:
      GITHUB_ACCESS_TOKEN:
      GITHUB_USER:
      TERRAFORM_TOKEN:
      TF_VAR_dnsimple_account:
      TF_VAR_dnsimple_token:
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: |-
        sudo apt update
        sudo apt install -y awscli docker
    - name: Setup AWS assume role
      run: |-
        read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
          < <(aws sts assume-role-with-web-identity \
              --role-arn "${AWS_ROLE_ARN}" \
              --role-session-name "${AWS_ROLE_SESSION_NAME}" \
              --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
              "$@" \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
        if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
            echo "Failed to assume role"
            exit 1
        else
            {
                echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
                echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
                echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
            } >>"$BASH_ENV"
            echo "Assume role with web identity succeeded"
        fi
    - name: Hadolint run
      run: |-
        source ${BASH_ENV}
        docker run --rm -i hadolint/hadolint < Dockerfile
    - name: Docker build
      run: docker build -t dnsfilter/${{ inputs.project_name }}:${{ github.sha }} .
    - name: Install trivy
      run: |-
        sudo apt update && sudo apt install curl
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
    - name: Scan the local image with trivy
      run: trivy image --exit-code 0 --no-progress dnsfilter/${{ inputs.project_name }}:${{ github.sha }}
    - name: Docker build, tag and push
      run: |-
        sudo apt update
        docker tag dnsfilter/${{ inputs.project_name }}:${{ github.sha }} ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.sha }}
        aws ecr get-login-password --region ${AWS_REGION_PROD} | docker login --username AWS --password-stdin ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/
        docker push ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION_PROD}.amazonaws.com/${{ inputs.project_name }}:${{ github.sha }}
  deploy-dev-k8s:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
    - build-push-docker-image
    env:
      AWS_ACCOUNT:
      AWS_DEFAULT_REGION:
      AWS_REGION_NON_PROD:
      AWS_REGION_PROD:
      AWS_ROLE_ARN:
      AWS_ROLE_SESSION_NAME:
      CLUSTER_NAME_APPS_NON_PROD:
      GITHUB_ACCESS_TOKEN:
      GITHUB_USER:
      TERRAFORM_TOKEN:
      TF_VAR_dnsimple_account:
      TF_VAR_dnsimple_token:
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Install dependencies
      run: |-
        sudo apt update
        sudo apt install -y awscli
    - name: Setup AWS assume role
      run: |-
        read -r AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN \
          < <(aws sts assume-role-with-web-identity \
              --role-arn "${AWS_ROLE_ARN}" \
              --role-session-name "${AWS_ROLE_SESSION_NAME}" \
              --web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
              "$@" \
              --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
              --output text)
        if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
            echo "Failed to assume role"
            exit 1
        else
            {
                echo "export AWS_ACCESS_KEY_ID=\"${AWS_ACCESS_KEY_ID}\""
                echo "export AWS_SECRET_ACCESS_KEY=\"${AWS_SECRET_ACCESS_KEY}\""
                echo "export AWS_SESSION_TOKEN=\"${AWS_SESSION_TOKEN}\""
            } >>"$BASH_ENV"
            echo "Assume role with web identity succeeded"
        fi
    - name: Update kubeconfig and deploy
      run: "source ${BASH_ENV}\ncurl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null\nsudo apt install apt-transport-https --yes\necho \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main\" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list\nsudo apt update\nsudo apt install -y helm\naws eks --region ${AWS_REGION_NON_PROD} update-kubeconfig --name ${CLUSTER_NAME_APPS_NON_PROD}\nhelm repo add dnsfilter https://raw.githubusercontent.com/DNSFilter/iac_helm_charts/main/ --username ${GITHUB_USER} --password ${GITHUB_ACCESS_TOKEN}\nhelm repo update \nhelm upgrade -i ${{ inputs.project_name }} -f ./iac/kubernetes/values-dev.yaml dnsfilter/service --version ${{ inputs.helm_chart_version }} --set image.tag=${{ github.sha }} --set ingressHost=\"${{ inputs.project_name }}.dev.${{ inputs.domain }}\" -n develop"
